repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

releases:
  - name: validator
    namespace: arrakis-evolution-chain
    chart: parity/node
    version: 5.1.0
    values:
      - image:
          repository: freeverseio/laos-evolution-node
          tag: {{ requiredEnv "TAG" }}
      - node:
          legacyRpcFlags: true
          chain: arrakis
          command: "node-template"
          replicas: 2
          chainData:
              volumeSize: 200Gi
          perNodeServices:
            relayP2pService:
              enabled: true
              type: LoadBalancer
            apiService:
              enabled: false
  - name: public-node
    namespace: arrakis-evolution-chain
    chart: parity/node
    version: 5.1.0
    values:
      - image:
          repository: freeverseio/laos-evolution-node
          tag: {{ requiredEnv "TAG" }}
      - node:
          legacyRpcFlags: true
          chain: arrakis
          command: "node-template"
          replicas: 1
          chainData:
              volumeSize: 200Gi
          perNodeServices:
            relayP2pService:
              enabled: true
              type: LoadBalancer