helmDefaults:
  createNamespace: false
  waitForJobs: true

environments:
  local:
    values:
    - usePersistentStorage: false
    - ingress:
        enabled: false
        host: localhost
  default:
    values:
    - usePersistentStorage: false
    - ingress:
        enabled: true
        host: arrakis.gorengine.com

namespace: arrakis-evolution-chain

releases:
- name: alice
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: v0.0.5
      args:
      - --chain=arrakis
      - --alice
  - ingress:
      enabled: {{ .Environment.Values.ingress.enabled }}
      host: alice.{{ .Environment.Values.ingress.host }}
  - service:
      type: ClusterIP

# - name: bob
#   chart: ./laos-evolution-node
#   values:
#   - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
#   - image:
#       tag: v0.0.5
#       args:
#       - --chain=arrakis
#       - --bob
#   - ingress:
#       enabled: {{ .Environment.Values.ingress.enabled }}
#       host: bob.{{ .Environment.Values.ingress.host }}