helmDefaults:
  createNamespace: false
  waitForJobs: true

environments:
  local:
    values:
    - usePersistentStorage: false
    - image:
        tag: c901deb33180b01cc076efc6a85a3bc2233795c1
  default:
    values:
    - usePersistentStorage: true
    - image:
        tag: c901deb33180b01cc076efc6a85a3bc2233795c1

namespace: arrakis-evolution-chain

releases:
- name: freeverse0
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ .Environment.Values.image.tag }}
      args:
      - --chain=arrakis
      - --validator
      - --name=freeverse0
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
  - service:
      type: LoadBalancer
      ports:
        p2p: true

- name: freeverse1
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ .Environment.Values.image.tag }}
      args:
      - --chain=arrakis
      - --validator
      - --name=freeverse1
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
  - service:
      type: LoadBalancer
      ports:
        p2p: true

- name: freeverse2
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ .Environment.Values.image.tag }}
      args:
      - --chain=arrakis
      - --name=freeverse2
      - --ws-external
      - --rpc-cors=all
      - --telemetry-url
      - "wss://telemetry.polkadot.io/submit/ 0"
  - service:
      ports:
        ws: true
  - ingress:
      enabled: true
      host: "arrakis.gorengine.com"