repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

releases:
  - name: validator
    namespace: arrakis-evolution-chain
    chart: parity/node
    version: 5.1.0
    values:
      - image:
          repository: freeverseio/laos-evolution-node
          tag: {{ requiredEnv "TAG" }}
      - node:
          chain: arrakis
          command: "node-template"
          replicas: 2
          role: "validator"
          chainData:
              volumeSize: 200Gi
          perNodeServices:
            relayP2pService:
              enabled: true
              type: LoadBalancer
          # legacyRpcFlags: true
          # allowUnsafeRpcMethods: true
  - name: public-node
    namespace: arrakis-evolution-chain
    chart: parity/node
    version: 5.1.0
    values:
      - image:
          repository: freeverseio/laos-evolution-node
          tag: {{ requiredEnv "TAG" }}
      - node:
          chain: arrakis
          command: "node-template"
          replicas: 1
          chainData:
              volumeSize: 200Gi
          perNodeServices:
            relayP2pService:
              enabled: true
              type: LoadBalancer
          legacyRpcFlags: true
      - ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
            nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
            nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
            nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
            nginx.ingress.kubernetes.io/websocket-services: "public-node"
            cert-manager.io/cluster-issuer: letsencrypt-freeverse
          rules:
          - host: arrakis.gorengine.com
            http:
              paths:
              - path: /evo
                pathType: Prefix
                backend:
                  service:
                    name: public-node
                    port:
                      name: websocket-rpc
          tls:
            - hosts:
              - arrakis.gorengine.com
              secretName: public-node-tls
