helmDefaults:
  createNamespace: false
  waitForJobs: true

environments:
  local:
    values:
    - usePersistentStorage: false
  default:
    values:
    - usePersistentStorage: true

namespace: arrakis-evolution-chain

releases:
- name: node0
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: test
      args:
      - --chain=arrakis
      - --validator
      - --name freeverse0
  - service:
      type: LoadBalancer

- name: node1
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: test
      args:
      - --chain=arrakis
      - --validator
      - --name freeverse1
  - service:
      type: LoadBalancer