helmDefaults:
  createNamespace: false
  waitForJobs: true

environments:
  local:
    values:
    - usePersistentStorage: false
    - ingress:
        enabled: false
  default:
    values:
    - usePersistentStorage: true
    - ingress:
        enabled: true

namespace: arrakis-evolution-chain

releases:
- name: freeverse0
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ requiredEnv "TAG" }}
      args:
      - --chain=arrakis
      - --validator
      - --name=freeverse0
  - service:
      type: LoadBalancer
      ports:
        p2p: true

- name: freeverse1
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ requiredEnv "TAG" }}
      args:
      - --chain=arrakis
      - --validator
      - --name=freeverse1
  - service:
      ports:
        p2p: true

- name: freeverse2
  chart: ./laos-evolution-node
  values:
  - usePersistentStorage: {{ .Environment.Values.usePersistentStorage }}
  - image:
      tag: {{ requiredEnv "TAG" }}
      args:
      - --chain=arrakis
      - --name=freeverse2
      - --ws-external
      - --rpc-cors=all
  - service:
      ports:
        ws: true
  - ingress:
      enabled: {{ .Values.ingress.enabled }}
      host: "arrakis.gorengine.com"